version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    # Weitere Einstellungen wie Ports, falls nötig

  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: wsjf_planning
      POSTGRES_USER: wsjf
      POSTGRES_PASSWORD: wsjfpass
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data: